SET SERVEROUTPUT ON FORMAT WRAPPED
SET TRIMSPOOL ON
SET PAGES 1000
SET LINES 500
WHENEVER SQLERROR EXIT FAILURE;
SPOOL R_Suite_br
DECLARE
BEGIN

  Utils.Clear_Log;
  Utils_TT.Run_Suite;

EXCEPTION
  WHEN OTHERS THEN
    Utils.Write_Other_Error;
END;
/
@L_Log_Default
SPOOL OFF